# LeetCode Problem 1693: Daily Leads and Partners
---
[Problem Link](https://leetcode.com/problems/daily-leads-and-partners/description/)

## Problem Description

Given a table `DailySales` with columns `date_id`, `make_name`, `lead_id`, and `partner_id`, find the number of distinct `lead_id`'s and distinct `partner_id`'s for each `date_id` and `make_name`.

Return the result table in any order.

### Example 1

**Input:**  
DailySales table:

| date_id   | make_name | lead_id | partner_id |
|-----------|-----------|---------|------------|
| 2020-12-8 | toyota    | 0       | 1          |
| 2020-12-8 | toyota    | 1       | 0          |
| 2020-12-8 | toyota    | 1       | 2          |
| 2020-12-7 | toyota    | 0       | 2          |
| 2020-12-7 | toyota    | 0       | 1          |
| 2020-12-8 | honda     | 1       | 2          |
| 2020-12-8 | honda     | 2       | 1          |
| 2020-12-7 | honda     | 0       | 1          |
| 2020-12-7 | honda     | 1       | 2          |
| 2020-12-7 | honda     | 2       | 1          |

**Output:**  

| date_id   | make_name | unique_leads | unique_partners |
|-----------|-----------|--------------|-----------------|
| 2020-12-8 | toyota    | 2            | 3               |
| 2020-12-7 | toyota    | 1            | 2               |
| 2020-12-8 | honda     | 2            | 2               |
| 2020-12-7 | honda     | 3            | 2               |

### Explanation

For 2020-12-8:
- Toyota gets leads = [0, 1] and partners = [0, 1, 2]
- Honda gets leads = [1, 2] and partners = [1, 2]

For 2020-12-7:
- Toyota gets leads = [0] and partners = [1, 2]
- Honda gets leads = [0, 1, 2] and partners = [1, 2]

## Approach to Solve the Problem

1. Group the data by `date_id` and `make_name`.
2. Count the number of unique `lead_id` and `partner_id` for each group.
3. Reset the index and rename the columns accordingly.

Happy coding! ðŸŽ‰

In [1]:
import pandas as pd


def daily_leads_and_partners(daily_sales):
    daily_sales = (
        daily_sales.groupby(["date_id", "make_name"])[["lead_id", "partner_id"]]
        .nunique()
        .reset_index()
    )
    daily_sales.columns = ["date_id", "make_name", "unique_leads", "unique_partners"]
    return daily_sales

In [2]:
# Data from Leetcode problem
data = [
    ["2020-12-8", "toyota", 0, 1],
    ["2020-12-8", "toyota", 1, 0],
    ["2020-12-8", "toyota", 1, 2],
    ["2020-12-7", "toyota", 0, 2],
    ["2020-12-7", "toyota", 0, 1],
    ["2020-12-8", "honda", 1, 2],
    ["2020-12-8", "honda", 2, 1],
    ["2020-12-7", "honda", 0, 1],
    ["2020-12-7", "honda", 1, 2],
    ["2020-12-7", "honda", 2, 1],
]

# Create a DataFrame
daily_sales = pd.DataFrame(
    data, columns=["date_id", "make_name", "lead_id", "partner_id"]
).astype(
    {
        "date_id": "datetime64[ns]",
        "make_name": "object",
        "lead_id": "Int64",
        "partner_id": "Int64",
    }
)

# Call the function
daily_leads_and_partners(daily_sales)

     date_id make_name  unique_leads  unique_partners
0 2020-12-07     honda             3                2
1 2020-12-07    toyota             1                2
2 2020-12-08     honda             2                2
3 2020-12-08    toyota             2                3